version: "2.4"
services:
   mlflow-tracker:
    container_name: mlflow
    image: ghcr.io/mlflow/mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./requirements/mlflow/data:/mlflow
    networks:
      vpcbr:
        ipv4_address: 10.6.0.6
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlflow/artifacts

  spark-worker:
    build:
      context: ./
      dockerfile: spark/Dockerfile
    depends_on:
      - mlflow-tracker
    volumes:
      - ./spark/scripts:/spark/scripts
    networks:
      vpcbr:
        ipv4_address: 10.6.0.3

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.6.0.0/16
         gateway: 10.6.0.1                   